//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace codxFrank.Test.Ioc.QueryAccountSummaryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueryAccountSummaryService.IQueryAccountSummaryService")]
    public interface IQueryAccountSummaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchTotalSummary", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchTotalSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.AccountQuery.AccountTotalSummary FetchTotalSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchTotalSummary", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchTotalSummaryResponse")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountQuery.AccountTotalSummary> FetchTotalSummaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchTaiwanDollarAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchTaiwanDollarAccountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.AccountUsage[] FetchTaiwanDollarAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchTaiwanDollarAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchTaiwanDollarAccountsResponse")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchTaiwanDollarAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchForeignExchangeAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchForeignExchangeAccountsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.AccountUsage[] FetchForeignExchangeAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchForeignExchangeAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchForeignExchangeAccountsRespon" +
            "se")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchForeignExchangeAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchAuthorizationAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchAuthorizationAccountsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.AccountUsage[] FetchAuthorizationAccounts(bool isForeign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchAuthorizationAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchAuthorizationAccountsResponse" +
            "")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchAuthorizationAccountsAsync(bool isForeign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchFundInvestmentItems", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchFundInvestmentItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.Investment.FundInvestmentItem[] FetchFundInvestmentItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchFundInvestmentItems", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchFundInvestmentItemsResponse")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.Investment.FundInvestmentItem[]> FetchFundInvestmentItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchLoanAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchLoanAccountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.Loan.LoanAccountInfo[] FetchLoanAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/FetchLoanAccounts", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/FetchLoanAccountsResponse")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.Loan.LoanAccountInfo[]> FetchLoanAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/QueryCreditCardSummary", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/QueryCreditCardSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.EnterpriseApplicationIntegrationError), Action="EAI operation", Name="EnterpriseApplicationIntegrationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ExternalSystemError), Action="External system call", Name="ExternalSystemError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.ValidationError), Action="Validation", Name="ValidationError", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.InternetBank.Domains.GeneralError), Action="GeneralError", Name="GeneralError", Namespace="")]
        Microsoft.InternetBank.Domains.QueryCreditCardSummary QueryCreditCardSummary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryAccountSummaryService/QueryCreditCardSummary", ReplyAction="http://tempuri.org/IQueryAccountSummaryService/QueryCreditCardSummaryResponse")]
        System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.QueryCreditCardSummary> QueryCreditCardSummaryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryAccountSummaryServiceChannel : codxFrank.Test.Ioc.QueryAccountSummaryService.IQueryAccountSummaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryAccountSummaryServiceClient : System.ServiceModel.ClientBase<codxFrank.Test.Ioc.QueryAccountSummaryService.IQueryAccountSummaryService>, codxFrank.Test.Ioc.QueryAccountSummaryService.IQueryAccountSummaryService {
        
        public QueryAccountSummaryServiceClient() {
        }
        
        public QueryAccountSummaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryAccountSummaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAccountSummaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAccountSummaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Microsoft.InternetBank.Domains.AccountQuery.AccountTotalSummary FetchTotalSummary() {
            return base.Channel.FetchTotalSummary();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountQuery.AccountTotalSummary> FetchTotalSummaryAsync() {
            return base.Channel.FetchTotalSummaryAsync();
        }
        
        public Microsoft.InternetBank.Domains.AccountUsage[] FetchTaiwanDollarAccounts() {
            return base.Channel.FetchTaiwanDollarAccounts();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchTaiwanDollarAccountsAsync() {
            return base.Channel.FetchTaiwanDollarAccountsAsync();
        }
        
        public Microsoft.InternetBank.Domains.AccountUsage[] FetchForeignExchangeAccounts() {
            return base.Channel.FetchForeignExchangeAccounts();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchForeignExchangeAccountsAsync() {
            return base.Channel.FetchForeignExchangeAccountsAsync();
        }
        
        public Microsoft.InternetBank.Domains.AccountUsage[] FetchAuthorizationAccounts(bool isForeign) {
            return base.Channel.FetchAuthorizationAccounts(isForeign);
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.AccountUsage[]> FetchAuthorizationAccountsAsync(bool isForeign) {
            return base.Channel.FetchAuthorizationAccountsAsync(isForeign);
        }
        
        public Microsoft.InternetBank.Domains.Investment.FundInvestmentItem[] FetchFundInvestmentItems() {
            return base.Channel.FetchFundInvestmentItems();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.Investment.FundInvestmentItem[]> FetchFundInvestmentItemsAsync() {
            return base.Channel.FetchFundInvestmentItemsAsync();
        }
        
        public Microsoft.InternetBank.Domains.Loan.LoanAccountInfo[] FetchLoanAccounts() {
            return base.Channel.FetchLoanAccounts();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.Loan.LoanAccountInfo[]> FetchLoanAccountsAsync() {
            return base.Channel.FetchLoanAccountsAsync();
        }
        
        public Microsoft.InternetBank.Domains.QueryCreditCardSummary QueryCreditCardSummary() {
            return base.Channel.QueryCreditCardSummary();
        }
        
        public System.Threading.Tasks.Task<Microsoft.InternetBank.Domains.QueryCreditCardSummary> QueryCreditCardSummaryAsync() {
            return base.Channel.QueryCreditCardSummaryAsync();
        }
    }
}
